import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/static/Header/page";
import Footer from "./components/static/Footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <head>
        <link rel="icon" href="/favicon.ico"/>
        </head>
        <body>
          <Header/>
          {children}
          <Footer/>
        </body>
      </html>
    </>
  );
}
